settings = {
    'api_key': 'eb5a249e88e6f45184e66384474fa048',
    'series_ids': [
        'FEDFUNDS', 'GDP', 'CPIAUCSL', 'CUSR0000SAH1', 'CPILFESL', 'PCE', 
        'PRFI', 'PNFI', 'EXPGS', 'HOUST', 'DSPI', 'DGS2', 'DGS5', 'DGS10', 
        'AAA', 'BAA', 'WTISPLC', 'IMPGS', 'GCE', 'FGCE', 'GDPCTPI', 
        'PCEPI', 'PCEPILFE', 'PAYEMS', 'UNRATE', 'INDPRO', 'CUMFNS','USREC'
    ],
    'start_date': '1976-01-01',
    'end_date': '2024-01-01',
    'frequency_map': {
        'FEDFUNDS': 'm',
        'GDP': 'q',
        'CPIAUCSL': 'm',
        'CUSR0000SAH1': 'm',
        'CPILFESL': 'm',
        'PCE': 'm',
        'PRFI': 'q',
        'PNFI': 'q',
        'EXPGS': 'q',
        'HOUST': 'm',
        'DSPI': 'm',
        'DGS2': 'd',
        'DGS5': 'd',
        'DGS10': 'd',
        'AAA': 'm',
        'BAA': 'm',
        'WTISPLC': 'm',
        'IMPGS': 'q',
        'GCE': 'q',
        'FGCE': 'q',
        'GDPCTPI': 'q',
        'PCEPI': 'm',
        'PCEPILFE': 'm',
        'BSHCFAW': 'm',
        'PAYEMS': 'm',
        'UNRATE': 'm',
        'INDPRO': 'm',
        'CUMFNS': 'm',
    },
    'dagshub_repo' : 'najibabounasr/MacroEconomicAPI',

}